services:
  - type: web
    name: tiktok-image-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 2 api_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: TIKTOK_REDIRECT_URI
        sync: false

